# scripts/react_overlay.py
"""React UI overlay adapter — Stage 5 skeleton (v0.5 H4).

Generates `frontend/src/api/<entity>.ts` fetch modules from the blueprint
entities and `endpoints.json` produced by Stage 3 (`3-mybatis/endpoints.json`).

Scope (H4 skeleton):
    - One TypeScript module per entity.
    - 2 standard helpers: `selectDataListMap`, `saveDataListMap`.
    - Plain `fetch()` — no SWR / React Query dependency in the generated code.

Conflict policy mirrors the nexacro adapter:
    - conflict-scan first; abort on existing file unless `overlay_force=True`
    - one-shot `.bak` backup on overwrite

Returns a report dict shaped like the nexacro report so callers can treat both
uniformly. Fields not produced by react are present but empty.
"""
import json
import pathlib

import ui_overlay_registry


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _load_endpoints(out_dir: pathlib.Path) -> dict:
    """Read endpoints.json emitted by Stage 3."""
    path = out_dir / "3-mybatis" / "endpoints.json"
    if not path.exists():
        return {}
    return json.loads(path.read_text(encoding="utf-8"))


def _fetch_module(entity_name: str, endpoints: dict) -> str:
    """Render a TypeScript fetch module for a single entity."""
    select_path = ""
    save_path = ""
    if endpoints:
        select_path = (
            endpoints.get("select_datalist_map", {}).get("path", "")
        )
        save_path = (
            endpoints.get("save_datalist_map", {}).get("path", "")
            or endpoints.get("insert_data", {}).get("path", "")
        )

    return (
        f"// AUTO-GENERATED by scripts/react_overlay.py — do not edit by hand\n"
        f"// Entity: {entity_name}\n\n"
        f"const SELECT_URL = {json.dumps(select_path)};\n"
        f"const SAVE_URL = {json.dumps(save_path)};\n\n"
        f"export async function selectDataListMap"
        f"(params: Record<string, unknown> = {{}}): Promise<unknown[]> {{\n"
        f"  const res = await fetch(SELECT_URL, {{\n"
        f"    method: 'POST',\n"
        f"    headers: {{ 'Content-Type': 'application/json' }},\n"
        f"    body: JSON.stringify(params),\n"
        f"  }});\n"
        f"  if (!res.ok) throw new Error(`select_datalist_map failed: ${{res.status}}`);\n"
        f"  const data = await res.json();\n"
        f"  return (data && data.{entity_name}) || [];\n"
        f"}}\n\n"
        f"export async function saveDataListMap"
        f"(rows: unknown[]): Promise<unknown> {{\n"
        f"  const res = await fetch(SAVE_URL, {{\n"
        f"    method: 'POST',\n"
        f"    headers: {{ 'Content-Type': 'application/json' }},\n"
        f"    body: JSON.stringify({{ {entity_name}: rows }}),\n"
        f"  }});\n"
        f"  if (!res.ok) throw new Error(`save_datalist_map failed: ${{res.status}}`);\n"
        f"  return res.json();\n"
        f"}}\n"
    )


def _empty_report() -> dict:
    return {
        "java_copied": [],
        "resources_copied": [],
        "xfdl_copied": [],
        "backed_up": [],
        "renamed_imports": 0,
        "menu_warning": None,
        "typedef_added": False,
        "conflicts": [],
        # H4: react-specific surface
        "react_api_written": [],
    }


# ---------------------------------------------------------------------------
# Adapter entry point
# ---------------------------------------------------------------------------

def run(
    *,
    out_dir: pathlib.Path,
    target_dir: pathlib.Path,
    domain_slug: str,
    domain_label: str,
    service_pascal: str,
    blueprint_entities: list[dict],
    overlay_force: bool = False,
    # Accepted for signature parity with nexacro adapter (unused by react)
    source_pkg_prefix: str = "com.example",
    target_pkg_prefix: str = "com.nexacro.uiadapter",
) -> dict:
    out_dir = pathlib.Path(out_dir)
    target_dir = pathlib.Path(target_dir)
    report = _empty_report()

    endpoints_doc = _load_endpoints(out_dir)
    per_entity = (
        endpoints_doc.get("endpoints", {})
        if isinstance(endpoints_doc, dict)
        else {}
    )

    api_root = target_dir / "frontend" / "src" / "api"

    # --- Conflict scan pass --------------------------------------------------
    planned: list[tuple[pathlib.Path, str]] = []
    conflicts: list[str] = []
    for e in blueprint_entities:
        name = e.get("name") or ""
        if not name:
            continue
        dest = api_root / f"{name}.ts"
        body = _fetch_module(name, per_entity.get(name, {}))
        planned.append((dest, body))
        if dest.exists() and not overlay_force:
            conflicts.append(str(dest))

    if conflicts:
        raise RuntimeError(
            "React overlay would overwrite existing files "
            "(use --overlay-force to allow):\n"
            + "\n".join(f"  - {p}" for p in conflicts)
        )

    # --- Apply --------------------------------------------------------------
    api_root.mkdir(parents=True, exist_ok=True)
    for dest, body in planned:
        if dest.exists() and overlay_force:
            bak = pathlib.Path(str(dest) + ".bak")
            if not bak.exists():
                bak.write_text(dest.read_text(encoding="utf-8"), encoding="utf-8")
                report["backed_up"].append(str(bak))
        dest.write_text(body, encoding="utf-8")
        report["react_api_written"].append(
            str(dest.relative_to(target_dir))
        )

    return report


# Register on import.
ui_overlay_registry.register("react", run)
