# scripts/react_overlay.py
"""React UI overlay adapter — Stage 5 skeleton (v0.5 H4).

Generates `frontend/src/api/<entity>.ts` fetch modules from the blueprint
entities and `endpoints.json` produced by Stage 3 (`3-mybatis/endpoints.json`).

Scope (H4 skeleton):
    - One TypeScript module per entity.
    - 2 standard helpers: `selectDataListMap`, `saveDataListMap`.
    - Plain `fetch()` — no SWR / React Query dependency in the generated code.

Conflict policy mirrors the nexacro adapter:
    - conflict-scan first; abort on existing file unless `overlay_force=True`
    - one-shot `.bak` backup on overwrite

Returns a report dict shaped like the nexacro report so callers can treat both
uniformly. Fields not produced by react are present but empty.
"""
import json
import pathlib

import ui_overlay_registry


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _load_endpoints(out_dir: pathlib.Path) -> dict:
    """Read endpoints.json emitted by Stage 3."""
    path = out_dir / "3-mybatis" / "endpoints.json"
    if not path.exists():
        return {}
    return json.loads(path.read_text(encoding="utf-8"))


def _fetch_module(entity_name: str, endpoints: dict) -> str:
    """Render a TypeScript fetch module for a single entity."""
    select_path = ""
    save_path = ""
    if endpoints:
        select_path = (
            endpoints.get("select_datalist_map", {}).get("path", "")
        )
        save_path = (
            endpoints.get("save_datalist_map", {}).get("path", "")
            or endpoints.get("insert_data", {}).get("path", "")
        )

    return (
        f"// AUTO-GENERATED by scripts/react_overlay.py — do not edit by hand\n"
        f"// Entity: {entity_name}\n\n"
        f"const SELECT_URL = {json.dumps(select_path)};\n"
        f"const SAVE_URL = {json.dumps(save_path)};\n\n"
        f"export async function selectDataListMap"
        f"(params: Record<string, unknown> = {{}}): Promise<unknown[]> {{\n"
        f"  const res = await fetch(SELECT_URL, {{\n"
        f"    method: 'POST',\n"
        f"    headers: {{ 'Content-Type': 'application/json' }},\n"
        f"    body: JSON.stringify(params),\n"
        f"  }});\n"
        f"  if (!res.ok) throw new Error(`select_datalist_map failed: ${{res.status}}`);\n"
        f"  const data = await res.json();\n"
        f"  return (data && data.{entity_name}) || [];\n"
        f"}}\n\n"
        f"export async function saveDataListMap"
        f"(rows: unknown[]): Promise<unknown> {{\n"
        f"  const res = await fetch(SAVE_URL, {{\n"
        f"    method: 'POST',\n"
        f"    headers: {{ 'Content-Type': 'application/json' }},\n"
        f"    body: JSON.stringify({{ {entity_name}: rows }}),\n"
        f"  }});\n"
        f"  if (!res.ok) throw new Error(`save_datalist_map failed: ${{res.status}}`);\n"
        f"  return res.json();\n"
        f"}}\n\n"
        f"// Growth-8: lane=react CSV exporter for RO/audit screens\n"
        f"function _csvEscape(v: unknown): string {{\n"
        f"  if (v == null) return '';\n"
        f"  const s = String(v);\n"
        f"  return /[\",\\n]/.test(s) ? '\"' + s.replace(/\"/g, '\"\"') + '\"' : s;\n"
        f"}}\n\n"
        f"export async function exportToCsv"
        f"(params: Record<string, unknown> = {{}}, filename: string = '{entity_name}.csv'): Promise<void> {{\n"
        f"  const rows = await selectDataListMap(params);\n"
        f"  if (!rows.length) return;\n"
        f"  const cols = Object.keys(rows[0] as Record<string, unknown>);\n"
        f"  const header = cols.join(',');\n"
        f"  const body = rows\n"
        f"    .map((r) => cols.map((c) => _csvEscape((r as Record<string, unknown>)[c])).join(','))\n"
        f"    .join('\\n');\n"
        f"  const blob = new Blob([header + '\\n' + body], {{ type: 'text/csv;charset=utf-8;' }});\n"
        f"  const url = URL.createObjectURL(blob);\n"
        f"  const a = document.createElement('a');\n"
        f"  a.href = url;\n"
        f"  a.download = filename;\n"
        f"  a.click();\n"
        f"  URL.revokeObjectURL(url);\n"
        f"}}\n"
    )


def _empty_report() -> dict:
    return {
        "java_copied": [],
        "resources_copied": [],
        "xfdl_copied": [],
        "backed_up": [],
        "renamed_imports": 0,
        "menu_warning": None,
        "typedef_added": False,
        "conflicts": [],
        # H4: react-specific surface
        "react_api_written": [],
        # Growth-8: list of entity names whose module includes exportToCsv
        "react_export_csv_added": [],
        # Gap 3: list of (entity_name, pattern) emitted as React page components
        "react_components_written": [],
    }


# ---------------------------------------------------------------------------
# Gap 3: Pattern-aware React page components (MD / TR depth)
# ---------------------------------------------------------------------------

def _pascal(name: str) -> str:
    return "".join(p[:1].upper() + p[1:] for p in name.split("_") if p)


def _find_md_child(entity_name: str, blueprint_entities: list[dict]) -> tuple[str, str] | None:
    """Find first 1:N relation where entity is the parent. Returns (child_name, fk_column)."""
    for e in blueprint_entities:
        if e.get("name") != entity_name:
            continue
        for rel in e.get("relations") or []:
            card = (rel.get("cardinality") or "").lower()
            if card in ("1:n", "1-n", "one-to-many"):
                child = rel.get("to") or rel.get("child")
                fk = (rel.get("fk") or {}).get("column") or "parent_id"
                if child:
                    return (child, fk)
    return None


def _find_self_parent_column(entity_name: str, blueprint_entities: list[dict]) -> str:
    """Detect self-hierarchy FK column. Falls back to 'parent_id'."""
    for e in blueprint_entities:
        if e.get("name") != entity_name:
            continue
        for rel in e.get("relations") or []:
            card = (rel.get("cardinality") or "").lower()
            if card == "self" or (rel.get("from") == rel.get("to")):
                return (rel.get("fk") or {}).get("column") or "parent_id"
    return "parent_id"


def _md_component(entity_name: str, child_name: str, fk_column: str) -> str:
    """Render React MD (master-detail) page component."""
    pascal = _pascal(entity_name)
    child_pascal = _pascal(child_name)
    return (
        f"// AUTO-GENERATED by scripts/react_overlay.py — Gap 3 MD pattern\n"
        f"// Entity: {entity_name} → child: {child_name} via {fk_column}\n"
        f"import {{ useEffect, useState }} from 'react';\n"
        f"import * as {entity_name}Api from '../api/{entity_name}';\n"
        f"import * as {child_name}Api from '../api/{child_name}';\n\n"
        f"type Row = Record<string, unknown>;\n\n"
        f"export default function {pascal}MDPage() {{\n"
        f"  const [masters, setMasters] = useState<Row[]>([]);\n"
        f"  const [selected, setSelected] = useState<Row | null>(null);\n"
        f"  const [children, setChildren] = useState<Row[]>([]);\n\n"
        f"  useEffect(() => {{\n"
        f"    {entity_name}Api.selectDataListMap().then((rows) => setMasters(rows as Row[]));\n"
        f"  }}, []);\n\n"
        f"  useEffect(() => {{\n"
        f"    if (!selected) {{ setChildren([]); return; }}\n"
        f"    const parentId = selected.id ?? selected.ID;\n"
        f"    {child_name}Api\n"
        f"      .selectDataListMap({{ {fk_column}: parentId }})\n"
        f"      .then((rows) => setChildren(rows as Row[]));\n"
        f"  }}, [selected]);\n\n"
        f"  async function saveChildren() {{\n"
        f"    await {child_name}Api.saveDataListMap(children);\n"
        f"  }}\n\n"
        f"  return (\n"
        f"    <div className=\"md-page\">\n"
        f"      <section className=\"md-master\">\n"
        f"        <h3>{pascal} (master)</h3>\n"
        f"        <table>\n"
        f"          <tbody>\n"
        f"            {{masters.map((m, i) => (\n"
        f"              <tr key={{i}} onClick={{() => setSelected(m)}}\n"
        f"                  className={{selected === m ? 'selected' : ''}}>\n"
        f"                {{Object.values(m).map((v, j) => (\n"
        f"                  <td key={{j}}>{{String(v ?? '')}}</td>\n"
        f"                ))}}\n"
        f"              </tr>\n"
        f"            ))}}\n"
        f"          </tbody>\n"
        f"        </table>\n"
        f"      </section>\n"
        f"      <section className=\"md-child\">\n"
        f"        <h3>{child_pascal} (lines)</h3>\n"
        f"        <table>\n"
        f"          <tbody>\n"
        f"            {{children.map((c, i) => (\n"
        f"              <tr key={{i}}>\n"
        f"                {{Object.values(c).map((v, j) => (\n"
        f"                  <td key={{j}}>{{String(v ?? '')}}</td>\n"
        f"                ))}}\n"
        f"              </tr>\n"
        f"            ))}}\n"
        f"          </tbody>\n"
        f"        </table>\n"
        f"        <button onClick={{saveChildren}}>Save</button>\n"
        f"      </section>\n"
        f"    </div>\n"
        f"  );\n"
        f"}}\n"
    )


def _tree_component(entity_name: str, parent_column: str) -> str:
    """Render React TR (tree-1-tier) page component."""
    pascal = _pascal(entity_name)
    return (
        f"// AUTO-GENERATED by scripts/react_overlay.py — Gap 3 TR pattern\n"
        f"// Entity: {entity_name} (self-hierarchy via {parent_column})\n"
        f"import {{ useEffect, useMemo, useState }} from 'react';\n"
        f"import * as {entity_name}Api from '../api/{entity_name}';\n\n"
        f"type Row = Record<string, unknown> & {{ id?: unknown; {parent_column}?: unknown }};\n"
        f"type Node = Row & {{ children: Node[] }};\n\n"
        f"function buildTree(rows: Row[]): Node[] {{\n"
        f"  const byId = new Map<unknown, Node>();\n"
        f"  rows.forEach((r) => byId.set(r.id ?? r.ID, {{ ...r, children: [] }}));\n"
        f"  const roots: Node[] = [];\n"
        f"  byId.forEach((node) => {{\n"
        f"    const pid = (node as Row)['{parent_column}'] ?? (node as Row)['{parent_column.upper()}'];\n"
        f"    const parent = pid != null ? byId.get(pid) : null;\n"
        f"    if (parent) parent.children.push(node);\n"
        f"    else roots.push(node);\n"
        f"  }});\n"
        f"  return roots;\n"
        f"}}\n\n"
        f"function TreeNode({{ node, depth }}: {{ node: Node; depth: number }}) {{\n"
        f"  const [open, setOpen] = useState(true);\n"
        f"  const label = String(node.name ?? node.NAME ?? node.id ?? node.ID ?? '');\n"
        f"  return (\n"
        f"    <div className=\"tree-node\">\n"
        f"      <div style={{{{ paddingLeft: depth * 16 }}}}>\n"
        f"        {{node.children.length > 0 && (\n"
        f"          <span onClick={{() => setOpen(!open)}}>{{open ? '▾' : '▸'}}</span>\n"
        f"        )}}\n"
        f"        <span>{{label}}</span>\n"
        f"      </div>\n"
        f"      {{open && node.children.map((c, i) => (\n"
        f"        <TreeNode key={{i}} node={{c}} depth={{depth + 1}} />\n"
        f"      ))}}\n"
        f"    </div>\n"
        f"  );\n"
        f"}}\n\n"
        f"export default function {pascal}TreePage() {{\n"
        f"  const [rows, setRows] = useState<Row[]>([]);\n"
        f"  useEffect(() => {{\n"
        f"    {entity_name}Api.selectDataListMap().then((r) => setRows(r as Row[]));\n"
        f"  }}, []);\n"
        f"  const tree = useMemo(() => buildTree(rows), [rows]);\n"
        f"  return (\n"
        f"    <div className=\"tree-page\">\n"
        f"      <h3>{pascal} (tree)</h3>\n"
        f"      {{tree.map((n, i) => <TreeNode key={{i}} node={{n}} depth={{0}} />)}}\n"
        f"      <div className=\"toolbar\">\n"
        f"        <button>루트 추가</button>\n"
        f"        <button>자식 추가</button>\n"
        f"        <button>삭제</button>\n"
        f"        <button>저장</button>\n"
        f"      </div>\n"
        f"    </div>\n"
        f"  );\n"
        f"}}\n"
    )


# ---------------------------------------------------------------------------
# Adapter entry point
# ---------------------------------------------------------------------------

def run(
    *,
    out_dir: pathlib.Path,
    target_dir: pathlib.Path,
    domain_slug: str,
    domain_label: str,
    service_pascal: str,
    blueprint_entities: list[dict],
    overlay_force: bool = False,
    # Accepted for signature parity with nexacro adapter (unused by react)
    source_pkg_prefix: str = "com.example",
    target_pkg_prefix: str = "com.nexacro.uiadapter",
) -> dict:
    out_dir = pathlib.Path(out_dir)
    target_dir = pathlib.Path(target_dir)
    report = _empty_report()

    endpoints_doc = _load_endpoints(out_dir)
    per_entity = (
        endpoints_doc.get("endpoints", {})
        if isinstance(endpoints_doc, dict)
        else {}
    )

    api_root = target_dir / "frontend" / "src" / "api"
    pages_root = target_dir / "frontend" / "src" / "pages"

    # --- Conflict scan pass --------------------------------------------------
    planned: list[tuple[pathlib.Path, str]] = []
    planned_components: list[tuple[pathlib.Path, str, str, str]] = []
    conflicts: list[str] = []
    for e in blueprint_entities:
        name = e.get("name") or ""
        if not name:
            continue
        dest = api_root / f"{name}.ts"
        body = _fetch_module(name, per_entity.get(name, {}))
        planned.append((dest, body))
        if dest.exists() and not overlay_force:
            conflicts.append(str(dest))

        pattern = (e.get("pattern") or "").upper()
        pascal = _pascal(name)
        if pattern == "MD":
            md = _find_md_child(name, blueprint_entities)
            if md:
                child_name, fk_col = md
                cdest = pages_root / name / f"{pascal}MDPage.tsx"
                cbody = _md_component(name, child_name, fk_col)
                planned_components.append((cdest, cbody, name, "MD"))
                if cdest.exists() and not overlay_force:
                    conflicts.append(str(cdest))
        elif pattern == "TR":
            parent_col = _find_self_parent_column(name, blueprint_entities)
            cdest = pages_root / name / f"{pascal}TreePage.tsx"
            cbody = _tree_component(name, parent_col)
            planned_components.append((cdest, cbody, name, "TR"))
            if cdest.exists() and not overlay_force:
                conflicts.append(str(cdest))

    if conflicts:
        raise RuntimeError(
            "React overlay would overwrite existing files "
            "(use --overlay-force to allow):\n"
            + "\n".join(f"  - {p}" for p in conflicts)
        )

    # --- Apply --------------------------------------------------------------
    api_root.mkdir(parents=True, exist_ok=True)
    for dest, body in planned:
        if dest.exists() and overlay_force:
            bak = pathlib.Path(str(dest) + ".bak")
            if not bak.exists():
                bak.write_text(dest.read_text(encoding="utf-8"), encoding="utf-8")
                report["backed_up"].append(str(bak))
        dest.write_text(body, encoding="utf-8")
        report["react_api_written"].append(
            str(dest.relative_to(target_dir))
        )
        if "export async function exportToCsv" in body:
            report["react_export_csv_added"].append(dest.stem)

    for dest, body, ename, pat in planned_components:
        dest.parent.mkdir(parents=True, exist_ok=True)
        if dest.exists() and overlay_force:
            bak = pathlib.Path(str(dest) + ".bak")
            if not bak.exists():
                bak.write_text(dest.read_text(encoding="utf-8"), encoding="utf-8")
                report["backed_up"].append(str(bak))
        dest.write_text(body, encoding="utf-8")
        report["react_components_written"].append(
            {"entity": ename, "pattern": pat,
             "path": str(dest.relative_to(target_dir))}
        )

    return report


# Register on import.
ui_overlay_registry.register("react", run)
